config/routes.rb
Rails.application.routes.draw do

  root to: 'manufacturers#index'

  resources :manufacturers, only: [:index, :show, :new, :create] do
    resources :cars, only: [:new, :create]
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :color, presence: true
  validates :mileage, presence: true, numericality: {
            greater_than_or_equal_to: 0
            }, allow_nil: false
  validates :year, presence: true, numericality: {
            greater_than_or_equal_to: 1920,
            less_than_or_equal_to: (Time.now.year + 1)
            }, allow_nil: false
  validates :manufacturer_id, presence: true
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true, uniqueness: true
  validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def new
    @car = Car.new
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
  end

  def create
    @car = Car.new(car_params)
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @car.manufacturer_id = @manufacturer.id

    if @car.save
      redirect_to @manufacturer
    else
      flash.now[:notice] = "Your Car was not succesfully submitted."
      render :new
    end
  end

  private

  def car_params
    params.require(:car).permit(:color, :year, :mileage, :description)
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

  def index
    @manufacturers = Manufacturer.all
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
    @cars = @manufacturer.cars
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      redirect_to @manufacturer
    else
      flash.now[:notice] = "Your Manufacturer was not succesfully submitted."
      render :new
    end
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/new.html.erb
<h1>Add a New Car</h1>

<%= simple_form_for([@manufacturer, @car]) do |f| %>
  <%= f.input :color, :input_html => { size: 20 } %>
  <%= f.input :mileage %>
  <%= f.input :year %>
  <%= f.input :description %>
  <%= f.button :submit, value: 'Create Car' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Car Listing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash.any? %>
  <%= flash[:notice] %>
  <br>
<% end %>

<%= yield %>

</body>
</html>

app/views/manufacturers/index.html.erb
<%= link_to "Add a New Manufacturer", new_manufacturer_path %>

<br><br>

<% @manufacturers.each do |m| %>
  <%= link_to m.name, manufacturer_path(m) %> - <%= m.country %>
  <br>
<% end %>

app/views/manufacturers/new.html.erb
<h1>Add a New Manufacturer</h1>

<%= simple_form_for(@manufacturer) do |f| %>
  <%= f.input :name, :input_html => { size: 40 } %>
  <%= f.input :country %>
  <%= f.button :submit, value: 'Create Manufacturer' %>
<% end %>

app/views/manufacturers/show.html.erb
<h1><%= @manufacturer.name %></h1>

<h4><%= @manufacturer.country %></h4>

<%= link_to "View All Manufacturers", manufacturers_path %> /

<%= link_to "Add a new Car", new_manufacturer_car_path(@manufacturer) %>

<br><br>

<table>
  <thead>
    <tr>
      <td>ID</td>
      <td>COLOR</td>
      <td>YEAR</td>
      <td>MILEAGE</td>
      <td>DESCRIPTION</td>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.id %></td>
        <td><%= car.color %></td>
        <td><%= car.year %></td>
        <td><%= car.mileage %></td>
        <td><%= car.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>